## **넘파이(Numerical Python)**

> ##### 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지     

<br>

루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 함 > 빠른 배열 연산속도 보장,

그러나 파이썬 언어 자체가 가지는 수행 성능의 제약이 존재함.

C/C++과 같은 저수준 언어 기반의 호환 API 제공

<br>

기능
- 배열 기반의 연산
- 다양한 데이터 핸들링 기능 제공

<br>

## **넘파이 ndarray 개요**

넘파이 모듈 입력 방법
``` python
import numpy as np
```

ndarray를 이용해 다차원 배열을 쉽게 생성, 다양한 연산 수행 가능.

<br>

### 넘파이 array( ) 함수
> 다양한 인자(ex.리스트)를 입력받아 ndarray로 변환하는 기능 수행.
>> ndarray 배열의 shape 변수는 행과 열의 수를 튜플 형태를 가지며 차원까지 알 수 있음.


```python
array1 = np. array([1, 2, 3])
print(`array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                    [2, 3, 4])
print('array2 type:', tyep(array2))
print('array2 array 형태:', array1.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shpe)
```

[ Output ]
```python
array1 type: <class 'numpy.ndarry'>
array1 array 형태 (3, )
array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)
```

**np.arrary( )** : ndarray로 변환을 원하는 객체를 인자로 입력 시 ndarray를 반환

**ndarray.shape** : ndarray의 차원과 크기를 튜플(tuple) 형태로 나타냄.


주의할 점: 명확히 차원의 차수를 변환하는 방법을 알아야 함.

**ndarray.ndim** 를 통해 array의 차원을 확인할 수 있음.


```python
print('array1 : {0}차원, array2:{1}차원, array{2}차원',fromat(array1.ndim,
                                                              array2.ndim, array3.ndim))
```

[ Output ]

```
array1: 1차원, array2: 2차원, array3: 2차원
```

array( ) 함수의 인자
: 배열의 차원과 크기를 쉽게 표현할 수 있으므로 파이썬의 리스트 객체가 주로 사용 됨.

> (예시) <br> 리스트 [ ] : 1차원, <br> 리스트의 리스트 [[ ]] : 2차원

<br>

##**ndarray의 데이터 타입**

ndarray 내의 데이터값: 숫자, 문자열, 불 등 모두 가능.


단, 연산의 특성상 ***같은 데이터 타입*** 만 가능 (dtype 속성으로 타입 확인 가능.)

```python
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type1(array1))
print(array1, array1.dtype)
```

[ Output ]

```python
<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3] int32
```

> 만약 데이터 유형이 섞여 있는 리스트를 ndarray로 변경할 시 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용.


```python
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0 ]
array3 = np.array(list3)
print(array3, array3.dtype)
```

[Output]

```python
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
[1. 2. 3.] float64
```

ndarray 내 데이터값의 타입변경은 astype( ) 메서드를 이용. ( *메모리를 절약하기 위함* )

> 예시


```python
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('float32')
print(array_int2, array_int2.dtype)
```

[ Output ]

```python
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
```

<br>

##**ndarray를 편리하게 생성하기 - arange, zeros, ones**

> arange( ): ndarray를 **연속값** 으로 초기화해 쉽게 생성 <br> zeros( ) : ndarray를 **0** 으로 초기화해 쉽게 생성 <br> ones( ) : ndarray를 **1** 으로 초기화해 쉽게 생성
> > 주로 테스트용 데이터, 대규모의 데이터 일괄 초기화를 위해 사용

<br>

### arange( )
> array를 range로 표현하는 것. 0부터 (함수 인자 값-1) 까지의 값을 순차적으로 ndarray의 데이터 값으로 변환

```python
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
```

[ Output ]

```python
[0 1 2 3 4 5 6 7 8 9]
int32 (10, )
```

default 함수 인자: stop 값. (start 값도 부여 가능)

<br>

###zeros( ), ones( )
> 튜플 형태의 shpae 값 입력시 각각 0 / 1으로 채운 같은 shape의 ndarray 반환 <br> 함수 인자로 dtype을 정해주지 않을시 default로 float64형의 ndarray를 채움.

```python
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)
```

[ Output ]

```python
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
```

<br>

## **ndarray의 차원과 크기를 변경하는 reshape( )**

> ndarray를 특정 차원 및 크기로 변환


```python

array1 = np.arange(10)
print('array1:|n', array1)

array2 = array1.reshape(2, 5)
print('array2:|n', array2)

array3 = array1.reshape(5, 2)
print('array3:|n', array3)
```

[ Output ]

```python
array1:
[0 1 2 3 4 5 6 7 8 9 ]
array1:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```
*reshape( )는 지정된 사이즈로 변경이 불가능하면 오류 발생.*

```python
array1.reshape(4, 3)
```

[ Output ]
```
ValueError                Traceback (most recent call last)



