<a href="https://colab.research.google.com/github/ewst22ParkSY/ESAA11_YB/blob/ESAA11_YB/0906_%EC%84%B8%EC%85%98_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [15]:
mt53 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(5,3)
print(mt53)
print()
mt32 = np.array([1,2,3,4,5,6]).reshape(3,2)
print(mt32)
print()
print(np.dot(mt53,mt32))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[1 2]
 [3 4]
 [5 6]]

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [43]:
A=np.arange(10)
A[A > 3] = -A[A > 3]
A[A <= -8] = -A[A <= -8]
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 ( 0+1+2+3+4-1)
10(0+1+2+3+4)

In [23]:
9, 10
# 모르겠다

range(0, 5)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> 합법적 (파이썬에서 사용 가능한 문법)
<br>
3,6 -> 합법적 X (파이썬에서 사용 불가능한 문법)

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
<br>
0
<br>
array(0)


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
import numpy as np

A1 = np.random.randint(0,10,10)
A2 = np.random.randint(0,10,10)

common_value = np.intersect1d(A1, A2)

print("A1:", A1)
print("A2:", A2)
print("common_value:", common_value)

Z1: [9 1 5 5 2 6 4 5 0 3]
Z2: [1 2 3 9 8 5 4 8 2 0]
common_value: [0 1 2 3 4 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

np.sqrt(-1)은 nan이 나오나,
np.emath.sqrt(-1)은 허수 i가 나온다.

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [27]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [50]:
A = float(input())
B = float(input())

sum_AB = np.add(A, B)
neg_A = np.negative(A)
div_neg_A = np.divide(neg_A, 2)
result = np.multiply(sum_AB, div_neg_A)

print(result)

4.5
2.5
-15.75


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [69]:
a=np.random.uniform(0,10,10)
print(a)
print(a-a%1)
print(a//1)

[7.70997828 2.89871921 2.81492658 7.21733989 8.71282206 2.29466109
 5.75540034 9.07945534 5.24411632 3.07990147]
[7. 2. 2. 7. 8. 2. 5. 9. 5. 3.]
[7. 2. 2. 7. 8. 2. 5. 9. 5. 3.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [53]:
b=np.random.uniform(0,4,25).reshape(5,5)
print(b)

[[2.01913032 1.9011868  3.66407352 2.6012987  3.42913083]
 [0.17161635 0.02476256 3.38337341 0.25784781 1.82561628]
 [3.86754325 3.24414992 3.4858186  0.36092722 1.8049667 ]
 [2.03195848 2.94111741 0.27967689 0.81540601 2.37099107]
 [3.31803253 2.67497915 2.09773639 0.73330434 0.84162088]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [70]:
ori_c = np.random.random(10)
sorted_c = np.sort(ori_c)
print(ori_c)
print(sorted_c)

[0.37734467 0.94688975 0.46650495 0.9960512  0.98673847 0.60869165
 0.99896063 0.65216629 0.68762532 0.67653538]
[0.37734467 0.46650495 0.60869165 0.65216629 0.67653538 0.68762532
 0.94688975 0.98673847 0.9960512  0.99896063]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [63]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A, B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [74]:
A = np.random.random((10,2))
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.8977919  0.99328191 1.08197351 0.97619645 0.66441114 1.03093283
 0.41204223 0.77304393 0.94077517 1.00560279]
[0.34484313 0.93351632 1.07044341 0.64574339 0.83617814 1.05132635
 0.53287923 1.07413786 0.1860472  1.18883816]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [79]:
Z = np.random.random(10)
print('최댓값을 0으로 바꾸기 전')
print(Z)
Z[Z.argmax()] = 0
print('최댓값을 0으로 바꾼 후')
print(Z)

최댓값을 0으로 바꾸기 전
[0.01815537 0.12573983 0.79887492 0.24535751 0.82057023 0.96668807
 0.14772582 0.36216525 0.66702864 0.77918483]
최댓값을 0으로 바꾼 후
[0.01815537 0.12573983 0.79887492 0.24535751 0.82057023 0.
 0.14772582 0.36216525 0.66702864 0.77918483]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [91]:
Z = np.arange(100)
v = np.random.uniform(0,100)

min = np.abs(Z-v).argmin()
closeset_value = Z[min]
print(closeset_value)

2


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [92]:
Z = np.arange(9).reshape(3,3)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [100]:
n = 10
p = 6
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

np.argsort(array[:, n])를 사용하면 된다. <br> column이 아닌 row에 따라 정렬하려면 np.argsort(array[n, : ])를 사용한다.

In [95]:
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[7 5 9]
 [2 4 4]
 [5 3 1]]
[[2 4 4]
 [5 3 1]
 [7 5 9]]


In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3