<a href="https://colab.research.google.com/github/ewst22ParkSY/ESAA11_YB/blob/ESAA11_YB/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [22]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
any_array = np.array([1, 2, 3, 4, 5])
memory_size = any_array.nbytes
print(memory_size)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
array1 = np.zeros(10)
array1[4]=1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
array_10to49 = np.arange(start=10, stop=50)
print(array_10to49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
array1 = np.arange(10)
R_vector = array1[::-1]
print(R_vector)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
array2 = np.arange(0,9)
matrix = array2.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
array3 = np.array([1, 2, 0, 0, 4, 0])
indices = array3[array3!=0]
print(indices)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [25]:
I_1 = np.identity(3)
I_2 = np.eye(3)
print(I_1)
print()
print(I_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [28]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.58232541 0.31144233 0.4168942 ]
  [0.21643133 0.81563032 0.78607722]
  [0.70462293 0.05943895 0.56795375]]

 [[0.32245125 0.38136569 0.69760895]
  [0.1717989  0.71190428 0.32116237]
  [0.15189304 0.73753329 0.09778347]]

 [[0.85078433 0.39323329 0.59314506]
  [0.62980642 0.20560946 0.2858886 ]
  [0.43703488 0.58069713 0.13808302]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [37]:
random_array_10x10 = np.random.random((10,10))
print(random_array_10x10)
minimum = np.min(random_array_10x10)
maximum = np.max(random_array_10x10)
print()
print('minimum of random_array_10x10:', minimum)
print()
print('maximum of random_array_10x10:', maximum)

[[0.61427874 0.89160746 0.09653309 0.282558   0.54078957 0.46732297
  0.40395663 0.68640192 0.2147031  0.60672984]
 [0.50065307 0.94007279 0.8709162  0.28920662 0.46848992 0.13146511
  0.61394722 0.76477191 0.18674857 0.79855251]
 [0.73260959 0.61565767 0.94205582 0.57791247 0.0272766  0.77423027
  0.97999156 0.63156261 0.79606211 0.48045338]
 [0.68352814 0.7069891  0.7674681  0.68690262 0.82624699 0.49262889
  0.06784104 0.30088586 0.42098428 0.59639499]
 [0.70611238 0.96545389 0.13471319 0.24886424 0.24978777 0.47750052
  0.04831057 0.17991939 0.11105768 0.87490123]
 [0.85814924 0.80512435 0.61167181 0.32646558 0.65160785 0.46054811
  0.58159663 0.04574924 0.70804004 0.51056626]
 [0.26915722 0.68640941 0.27719214 0.18159916 0.867981   0.31935376
  0.53959875 0.42766491 0.65979906 0.90219163]
 [0.20216807 0.73212551 0.51724522 0.19855844 0.28861071 0.73659821
  0.5882992  0.80373631 0.91791616 0.10892421]
 [0.2010967  0.72001095 0.930778   0.81625241 0.55557144 0.3083774
  0.38824484 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [35]:
array30 = np.random.random(30)
print('mean value:', np.mean(array30))

mean value: 0.5621942926978655


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [41]:
array01 = np.ones((4,4))
array01[0, :] = 0
array01[-1, :] = 0
array01[:, 0] = 0
array01[:, -1] = 0
print(array01)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan / False / False / False / True / False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [8]:
array4 = np.zeros([5,5])
array4[1,0] = 1
array4[2,1] = 2
array4[3,2] = 3
array4[4,3] = 4
print(array4)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [13]:
array5 = np.zeros([8,8])
array5[1::2, ::2] = 1
array5[::2, 1::2] = 1
print(array5)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [14]:
shape = (6,7,8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [16]:
array6 = np.random.random((5,5))
a6_std = np.std(array6)
a6_ave = np.mean(array6)
normalized_array = (array6 - a6_ave) / a6_std
print(normalized_array)

[[-1.05463623  0.9127166   0.53095258  0.07994659  1.10158333]
 [-1.27569953  1.53759683 -0.65958952 -1.71122962  0.38399925]
 [ 0.77448534  1.42431326 -1.67613642 -1.03066543  0.50984499]
 [-0.72799822 -0.70799875  0.36191576 -1.30400319  0.7396257 ]
 [ 1.35676709  0.57453133  0.8734482  -0.04161626 -0.97215369]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [21]:
RGBA = np.dtype([('Red', np.ubyte), ('Green', np.ubyte) , ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(RGBA)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]
