<a href="https://colab.research.google.com/github/ewst22ParkSY/ESAA11_YB/blob/ESAA11_YB/ESAA_YB_WEEK1_transcript.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **넘파이(Numerical Python)**

> ##### 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지     

<br>

루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 함 > 빠른 배열 연산속도 보장,

그러나 파이썬 언어 자체가 가지는 수행 성능의 제약이 존재함.

C/C++과 같은 저수준 언어 기반의 호환 API 제공

<br>

기능
- 배열 기반의 연산
- 다양한 데이터 핸들링 기능 제공

<br>

## **넘파이 ndarray 개요**

넘파이 모듈 입력 방법
``` python
import numpy as np
```

ndarray를 이용해 다차원 배열을 쉽게 생성, 다양한 연산 수행 가능.

<br>

### 넘파이 array( ) 함수
> 다양한 인자(ex.리스트)를 입력받아 ndarray로 변환하는 기능 수행.
>> ndarray 배열의 shape 변수는 행과 열의 수를 튜플 형태를 가지며 차원까지 알 수 있음.


```python
array1 = np. array([1, 2, 3])
print(`array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                    [2, 3, 4])
print('array2 type:', tyep(array2))
print('array2 array 형태:', array1.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shpe)
```

[ Output ]
```python
array1 type: <class 'numpy.ndarry'>
array1 array 형태 (3, )
array2 type: <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)
```

**np.arrary( )** : ndarray로 변환을 원하는 객체를 인자로 입력 시 ndarray를 반환

**ndarray.shape** : ndarray의 차원과 크기를 튜플(tuple) 형태로 나타냄.


주의할 점: 명확히 차원의 차수를 변환하는 방법을 알아야 함.

**ndarray.ndim** 를 통해 array의 차원을 확인할 수 있음.


```python
print('array1 : {0}차원, array2:{1}차원, array{2}차원',fromat(array1.ndim,
                                                              array2.ndim, array3.ndim))
```

[ Output ]

```
array1: 1차원, array2: 2차원, array3: 2차원
```

array( ) 함수의 인자
: 배열의 차원과 크기를 쉽게 표현할 수 있으므로 파이썬의 리스트 객체가 주로 사용 됨.

> (예시) <br> 리스트 [ ] : 1차원, <br> 리스트의 리스트 [[ ]] : 2차원

<br>

##**ndarray의 데이터 타입**

ndarray 내의 데이터값: 숫자, 문자열, 불 등 모두 가능.


단, 연산의 특성상 ***같은 데이터 타입*** 만 가능 (dtype 속성으로 타입 확인 가능.)

```python
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type1(array1))
print(array1, array1.dtype)
```

[ Output ]

```python
<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3] int32
```

> 만약 데이터 유형이 섞여 있는 리스트를 ndarray로 변경할 시 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용.


```python
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0 ]
array3 = np.array(list3)
print(array3, array3.dtype)
```

[Output]

```python
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11
[1. 2. 3.] float64
```

ndarray 내 데이터값의 타입변경은 astype( ) 메서드를 이용. ( *메모리를 절약하기 위함* )

> 예시


```python
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('float32')
print(array_int2, array_int2.dtype)
```

[ Output ]

```python
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
```

<br>

##**ndarray를 편리하게 생성하기 - arange, zeros, ones**

> arange( ): ndarray를 **연속값** 으로 초기화해 쉽게 생성 <br> zeros( ) : ndarray를 **0** 으로 초기화해 쉽게 생성 <br> ones( ) : ndarray를 **1** 으로 초기화해 쉽게 생성
> > 주로 테스트용 데이터, 대규모의 데이터 일괄 초기화를 위해 사용

<br>

### arange( )
> array를 range로 표현하는 것. 0부터 (함수 인자 값-1) 까지의 값을 순차적으로 ndarray의 데이터 값으로 변환

```python
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
```

[ Output ]

```python
[0 1 2 3 4 5 6 7 8 9]
int32 (10, )
```

default 함수 인자: stop 값. (start 값도 부여 가능)

<br>

###zeros( ), ones( )
> 튜플 형태의 shpae 값 입력시 각각 0 / 1으로 채운 같은 shape의 ndarray 반환 <br> 함수 인자로 dtype을 정해주지 않을시 default로 float64형의 ndarray를 채움.

```python
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)
```

[ Output ]

```python
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
```

<br>

## **ndarray의 차원과 크기를 변경하는 reshape( )**

> ndarray를 특정 차원 및 크기로 변환


```python

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)
```

[ Output ]

```python
array1:
[0 1 2 3 4 5 6 7 8 9 ]
array1:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```
*reshape( )는 지정된 사이즈로 변경이 불가능하면 오류 발생.*

```python
array1.reshape(4, 3)
```

[ Output ]
```
ValueError                             Traceback (most recent call last)
<ipython-input-83-a40469ec5825> in <module>( )
----> 1 array1.reshape(4, 3)
ValueError: cannot reshape array of size 10 into shape(4, 3)
```

예제)
reshape( )에 -1값을 인자로 적용한 경우에 ndarray의 size 변경방법

```python
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)
```

[ Output ]

``` python
[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)
```

하단의 예제의 경우 10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 열로 변경 불가하기에 에러 발생.

```python
array1 = np.arange(10)
array4 = array1.reshape(-1,4)
```

[ Output ]

```python
ValueError                                Traceback (most recent call last)
{ipython-input-100-07da9760475e> in <module>()
      1 array1 = np.arange(10)
----> 2 array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)
```

<br>

여러개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 사용.

예제 (ndarray는 tolist메서드를 이용해 리스트 자료형으로 변환 가능)
```python
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)
```

[ Output ]

```python
array3d:
 [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
```

<br>

##**넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexting)**

> ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 하는 것



1.   특정한 데이터만 추출: 원하는 위치의 인덱스 값 지정
2.   슬라이싱(Slicing): 연속된 인덱스상의 ndarray 추출 방식. ' :(콜론) ' 기호 사이에 시작 인덱스와 종료 인덱스 표시. (시작 인덱스부터 종료 인덱스-1 위치까지 반환)
3.   팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정, 해당 위치 데이터 반환
4.   불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합 기반으로 True에 해당하는 인덱스 위치의 데이터 반환


###단일 값 추출
> ndarray 객체에 해당하는 위치의 인덱스 값을 [ ] 안에 입력

```python
# 1부터 9까지 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))
```

[ Output ]

```python
array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
```

> 인덱스 추출 후에는 더 이상 ndarray 타입이 아니라 ndarray 내의 데이터값을 의미함.


<br>

*인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터 추출 가능.*

```python
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])
```

[ Output ]
```python
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
```

<br>

*단일 인덱스 활용해 ndarray 내의 데이터 값 간단히 수정 가능*

```python
array1[0] = 9
array1[8]= 0
print('array1:', array1)
```

[ Output ]

```python
array1: [9 2 3 4 5 6 7 8 0]
```

<br>

*다차원 array에서 단일 값 추출*

```python
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0 index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1 index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0 index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2 index 가리키는 값:', array2d[2, 2])
```

[ Output ]

```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9
```

*알아둘 것 - axis 0 : 로우 방향의 축(행), axis 1: 칼럼 방향의 축(열)*

###슬라이싱
> ' :(콜론) ' 기호를 이용, 연속한 데이터를 슬라이싱해 추출. <br> 슬라이싱, 팬시 인덱싱, 불린 인덱싱 추출 데이터는 모두 ndarray 타입.
<br> ':' 사이에 시작 인덱스와 종료 인덱스 표시 시, 시작 인덱스 ~ 종료 인덱스-1 위치 데이터 ndarray 반환.
<br>

예시

```
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))
```

[ Output ]

```python
[1 2 3]
<class 'numpy.ndarray'>
```

**슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능.**

>1.    ':' 기호 앞에 시작 인덱스 생략 시 처음 인덱스 0으로 간주
2.    ':' 기호 뒤에 종료 인덱스 생략 시 맨 마지막 인덱스로 간주
3.    ':' 기호 앞/뒤에 시작/종료 인덱스를 생략시 자동으로 맨 처음/맨 마지막 인덱스로 간주

```python
array1 = np.arange(start=1, stop=10)
array4 = array1[ :3]
print(array4)

array5 = array1[3: ]
print(array4)

array6 = array1[ : ]
print(array6)
```

[ Output ]
```python
[1 2 3]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
```

*2차원 ndarray 슬라이싱의 경우 1차원과 유사하나, 콤마로 로우와 칼럼 인덱스를 지칭함.*

```python
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, : ] \n', array2d[1:3, :])
print('array2d[：, :] \n', array2d[:, :])
print('array2d[:2, 1 : ] \n', array2d[:2, 1:])
print('array2d[ :2, 0] \n', array2d[:2, 0])
```

[ Output ]
```python
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, : ]
 [[4 5 6]
 [7 8 9]]
array2d[：, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1 : ]
 [[2 3]
 [5 6]]
array2d[ :2, 0]
 [1 4]
 ```

*2차원 ndarray 뒤에 오는 인덱스를 없앨 시 1차원(첫번째 행/열)을 반환.*

 ```python
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)
```

[ Output ]

```python
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)
```
<br>

###팬시 인덱싱(Fancy Indexing)
> 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱시 방식.

```python
array1d = np.arange(start=1, stop =10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1] 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]=> ', array5.tolist())
```

[ Output ]
```python
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1] 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]=>  [[1, 2, 3], [4, 5, 6]]
```

###불린 인덱싱(Boolean indexting)

> 조건 필터링과 검색 동시 가능

```python
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5 ]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)
```

[ Output ]
```python
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]
```

<br>

*조건 필터링 과정*

```python
array1d > 5
```

[ Output ]
```python
array([False, False, False, False, False,  True,  True,  True,  True])
```

1.   ndarray 객체에 조건식을 붙이면 True와 False로 이뤄진 ndarray 객채 반환.
2.   반환된 array는 True와 False로 조건에 따라 반환됨.
3.   인덱싱을 지정하는 [ ] 내에 입력할 시 False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환, 인덱스 위치의 데이터만 반환.

```python
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean+indexes]
print('불린 인덱스로 필터링 결과 :', array3)
```

[ Output ]
```
불린 인덱스로 필터링 결과 : [6 7 8 9]
```

즉, 하단의 인덱스 집합을 만들어 대입한 것과 동일.

```
indexes = np.array([5, 6, 7, 8])
array4 = array1[indexes]
print('일반 인덱스로 필터링 결과 :', array4)
```

[ Output ]
```
일반 인덱스로 필터링 결과 : [6 7 8 9]
```

***인덱싱 동작 단계 도식화***
1.   ndarray의 필터링 조건 [ ] 안에 기재
2.   False 값은 무시, True 값이 있는 인덱스 값 저장
3.   저장된 인덱스 데이터 세트로 ndarray 조회

<br>
<br>

##**행렬의 정렬 - sort( )와 argsort( )**

###행렬 정렬
1.   np.sort( ): 넘파이에서 sort( )를 호출하는 방식
2.   ndarray.sort( ): 행렬 자체에서 sort( )를 호출하는 방식

> 차이점
<br>
np.sort( ): 원 행렬은 유지한 채 정렬된 행렬 반환
<br>
ndarray.sort( ): 원 행렬 자체를 정렬한 형태로 변환, 반환 값 None.

*예제*
```python
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print ('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)
```

[ Output ]
```python
원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]
```

<br>

***모두 기본적으로 오름차순으로 행렬 내 원소 정렬***

***내림차순으로 정렬하기 위해서는 [::-1] 적용.***

```python
sort_array1_desc = np.sort(org_array)[::-1]
print('내립차순으로 정렬:', sort_array1_desc)
```

[ Output ]
```python
내림차순으로 정렬: [9 5 3 1]
```

<br>

*axis 축 값 설정을 통해 로우, 칼럼 방향 정렬 수행 가능*

```python
array2d = np.array([[8, 12],
                    [7,1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)
```

[ Output ]
```python
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]
 ```

<br>

###정렬된 행렬의 인덱스 반환하기
np.argsort( ): 원본 행렬이 정리되었고, 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 경우 이용

```python
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
```

[ Output ]
```python
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
```

*오름차순이 아닌 내림차순으로 정렬 시 원본 행렬의 인덱스를 구하는 것도 동일하게 [::-1] 적용*

```python
ort_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)
```

[ Output ]
```
행렬 내림차순 정렬 시 원본 행렬의 인덱스:[ 2 3 0 1]
```

ndarray는 메타 데이터(ex. RDBMS의 TABLE, 판다스 DataFrame 칼럼)를 가질 수 없음. -> 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray를 가져야함.

예제

```python
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])
```

[ Output ]
```
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
```

<br>
<br>

##선형대수 연산 - 행렬 내적과 전치 행렬 구하기


###행렬 내적(행렬 곱)
> np.dot( )을 이용해 계산 가능.
<br>
<br> 두 행렬의 내적이란?
> >왼쪽 행렬의 로우(행)과 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 더한 값.

```python
A = np.array( [[1, 2, 3],
               [4, 5, 6]] )

B = np.array( [[7, 8],
               [9, 10],
               [11, 12]] )

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)
```

[ Output ]
```python
행렬 내적 결과:
 [[ 58  64]
 [139 154]]
```


###전치 행렬
> 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
<br> 넘파이의 transpose( )를 이용해 구할 수 있음

```python
A = np.array([[1, 2],
              [3, 4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)
```

[ Output ]

```python
A의 전치 행렬:
 [[1 3]
 [2 4]]
```






